name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  EXECUTABLE: activitist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test
      run: go test -v .

    - name: Build
      run: go build -o $EXECUTABLE -v . 

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build
    steps:
    - name: Echo
      run: echo "Deploying $EXECUTABLE"
